MarketPlace/marketplace/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web_shop import urls as shop_urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include(shop_urls)),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MarketPlace/web_shop/urls.py
from django.conf.urls import url
from .forms import CustomRegistrationForm
from registration.backends.simple.views import RegistrationView
from web_shop import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search[/]$', views.search, name='search'),
    url(r'^addproduct[/]$', views.add_product),
    url(r'^product/(?P<p_id>\w+)[/]$', views.product_detail),
    url(r'^product/(?P<p_id>\w+)/edit[/]$', views.edit_product),
    url(r'^product/(?P<p_id>\w+)/cart$', views.product_cart),
    url(r'^product/(?P<p_id>\w+)/wish$', views.product_wishlist),
    url(r'^image/(?P<img_id>\w+)/$', views.delete_image),
    url(r'^category/(?P<category_name>\w+)[/]$', views.category_view),
    url(r'^login/$', views.signin),
    url(r'^logout/$', views.logout_user),
    url(r'^register/$', views.register),
    url(r'^editdetails/$', views.edit_details),
    url(r'^cart[/]$', views.cart_view),
    url(r'^cart/checkout[/]$', views.checkout),
    url(r'^cart/(?P<p_id>\w+)/update$', views.cart_update),
    url(r'^chat[/]$', views.chat, name='chat'),
    url(r'^chat-reload[/]$', views.chat_reload, name='chat-reload'),
    url(r'^listusers/$', views.listusers),
    url(r'^listsales/$', views.listsales),
    url(r'^sales-details/(?P<s_id>\w+)[/]$', views.sales_details),
    url(r'^contact/$', views.contact),
    url(r'^listcontacts/$', views.listcontacts),
    url(r'^wishlist[/]$', views.wishlist),
    url(r'^wishlist/(?P<p_id>\w+)[/]$', views.wishlist_update),
    url(r'^wishlist/(?P<p_id>\w+)/cart[/]$', views.wishlist_cart),
    url(r'^listaddresses/$', views.listaddresses),
    url(r'^editaddress/(?P<uid>\w+)[/]$', views.edit_address),
    url(r'^defaultaddress/(?P<uid>\w+)[/]$', views.default_address),
    url(r'^addaddress/$', views.add_address),
    url(r'^notifications/$', views.listnotifications),
    url(r'^listcategories/$', views.listcategories),
    url(r'^editcategory/(?P<uid>\w+)[/]$', views.edit_category),
    url(r'^addcategory/$', views.add_category)
]

MarketPlace/cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'))
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

MarketPlace/web_shop/models.py
from django.db import models
from django.utils import timezone
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType


fs = FileSystemStorage()


class Product(models.Model):
    """"""
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    visible = models.BooleanField(default=False)
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
    )
    tags = models.ManyToManyField('Tag', blank=True)
    thumbnail = models.ImageField(storage=fs)
    main_image = models.ImageField(storage=fs)
    added_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def _thumb(self):
        return '<img width="100" src="/media/%s">' % self.thumbnail
    _thumb.allow_tags = True

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        thumb_storage, thumb_path = self.thumbnail.storage, self.thumbnail.path
        image_storage = self.main_image.storage
        image_path = self.main_image.path

        # Delete the model before the file
        super(Product, self).delete(*args, **kwargs)
        # Delete the file after the model
        thumb_storage.delete(thumb_path)
        image_storage.delete(image_path)


class Category(models.Model):
    name = models.CharField(max_length=100, default='all')
    main_image = models.ImageField(storage=fs, default='hat.jpg')

    parent = models.ForeignKey("self", null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Raise on circular reference
        parent = self.parent
        while parent is not None:
            if parent == self:
                raise(RuntimeError, "Circular references not allowed")
            parent = parent.parent

        super(Category, self).save(*args, **kwargs)

    @property
    def children(self):
        return self.category_set.all().order_by("name")

    @property
    def get_parent_path(self):
        path = [self.name]
        parent = self.parent
        while parent is not None:
            path.append(parent.name)
            parent = parent.parent
        return path[::-1]

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Image(models.Model):
    image = models.ImageField(storage=fs)
    description = models.TextField()
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
    )

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.image.storage, self.image.path
        # Delete the model before the file
        super(Image, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

    def _img(self):
        return '<img width="300" src="/media/%s">' % self.image
    _img.allow_tags = True


class ChatHistory(models.Model):
    origin = models.CharField(max_length=30)
    to = models.CharField(max_length=30)
    message = models.TextField()

class Address(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    # will make sense with more than one address:
    default = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)

    number_street = models.CharField(max_length=92)
    suburb = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    region = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    postcode = models.CharField(max_length=30)

    def __unicode__(self):
        return self.number_street+' '+self.suburb+', '+self.city+' '+self.region+', '+self.country+' '+str(self.postcode)


class SalesOrder(models.Model):
    buyer = models.ForeignKey(User)
    address = models.ForeignKey(Address)
    created_on = models.DateTimeField(default=timezone.now)

    STATUSES = (
        ('new', 'New Order'),
        ('shipped', 'Order Shipped'),
        ('completed', 'Order Completed'),
        ('cancelled', 'Order Cancelled'),
    )
    status = models.CharField(
        max_length=20,
        choices=STATUSES,
        default='new')


class OrderItem(models.Model):
    order = models.ForeignKey(SalesOrder)
    quantity = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=18, decimal_places=2)
    # product as generic relation
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)


class WishList(models.Model):
    user = models.ForeignKey(User)


class WishListItem(models.Model):
    wishlist = models.ForeignKey(WishList)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    def __unicode__(self):
        return self.product.__class__.__name__

    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

class Contact(models.Model):
	subject = models.CharField(max_length=50)
	types = (
                ('general', 'Report general issue'),
                ('feedback', 'Give us feedback'),
				('refunds', 'Refund and Cancellation'),
				('missing', 'Where is my stuff?'),
				('violation', 'Report violation of Terms of Service'),
				('phishing', 'Report a phishing incident'),

			)
	message_type = models.CharField(
		max_length=20,
        choices=types,
        default='general')
	message = models.TextField()
	email = models.EmailField()
	statuses = (('open','Open'),('close','Closed'))
	status = models.CharField(
		max_length=6,
        choices=statuses,
        default='open')

class Notification(models.Model):
    to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    notif = models.CharField(max_length=30)
    link = models.CharField(max_length=100)

MarketPlace/web_shop/forms.py
from django import forms
from registration.forms import RegistrationFormUniqueEmail
from registration.forms import RegistrationFormTermsOfService
from web_shop.models import Category, Image


class ProductForm(forms.Form):
    # need to check that the name is only spaces or alpha-num or spaces
    name = forms.CharField(max_length=100, required=True)
    description = forms.CharField(required=True, widget=forms.Textarea)
    price = forms.DecimalField(required=True, max_digits=20, decimal_places=2)
    visible = forms.BooleanField(initial=False, required=False)
    tags = forms.CharField(
        required=False, widget=forms.Textarea,
        label='Comma Separated Tags')
    thumbnail = forms.ImageField(label='Thumbnail')
    main_image = forms.ImageField(label='Main Image')

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ChoiceField(
            choices=[ (c.pk, c.name) for c in Category.objects.all()])

    def clean_tags(self):
        data = self.cleaned_data['tags']
        data = data.split(',')
        return data

class EditProductForm(ProductForm):
    thumbnail = forms.ImageField(label='Thumbnail', required=False)
    main_image = forms.ImageField(label='Main Image', required=False)

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Image
        fields = ('image',)


class SearchForm(forms.Form):
    search = forms.CharField(required=True)


class CartForm(forms.Form):
    quantity = forms.IntegerField(initial=1, required=False, min_value=0)
    update = forms.BooleanField(required=False, initial=True)


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', required=True)
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput())


class CustomRegistrationForm(RegistrationFormUniqueEmail, RegistrationFormTermsOfService):
    pass

class EditCredentialsForm(forms.Form):
    firstName = forms.CharField(label='First Name', required=False)
    lastName = forms.CharField(label='Last Name', required=False)
    email = forms.EmailField(label='Email*', required=True)

    oldPass = forms.CharField(label='Current Password*', required=True, widget=forms.PasswordInput())

    newPass = forms.CharField(label='New Password', required=False, widget=forms.PasswordInput())
    retypeNewPass = forms.CharField(label='Retype New Password', required=False, widget=forms.PasswordInput())

    def clean(self):
        password1 = self.cleaned_data.get('newPass')
        password2 = self.cleaned_data.get('retypeNewPass')

        if (password1) and (password1 != password2):
            raise forms.ValidationError("New password don't match")

        return self.cleaned_data

class ChatForm(forms.Form):
    chat = forms.CharField(required=True)

class MessageForm(forms.Form):
    to = forms.CharField(widget=forms.HiddenInput())
    message = forms.CharField(required=True)


class AddressForm(forms.Form):
    number_street = forms.CharField(label='House number and street name', required=True)
    suburb = forms.CharField(required=True)
    city = forms.CharField(required=True)
    region = forms.CharField(required=True)
    country = forms.CharField(required=True)
    postcode = forms.CharField(required=True)


class ContactForm(forms.Form):
    subject = forms.CharField(required=True)
    types = (
                ('refunds', 'Refund and Cancellation'),
                ('missing', 'Where is my stuff?'),
                ('violation', 'Report violation of Terms of Service'),
                ('phishing', 'Report a phishing incident'),
                ('general', 'Report general issue'),
            )
    message_type = forms.CharField(label='Type',widget=forms.Select(choices=types))
    message = forms.CharField(widget=forms.Textarea, required=True)
    email = forms.EmailField(required=True)


class DisplayTypeForm(forms.Form):
    display_type = forms.ChoiceField(widget=forms.RadioSelect, choices=(("box", "Box"), ("details", "Details"), ("mix", "Mix")))


class SortTypeForm(forms.Form):
    options = (
        ("AtoZ", "A to Z"),
        ("ZtoA", "Z to A"),
        ("priceLow", "Price Low to High"),
        ("priceHigh", "Price High to Low")
        )
    sortType = forms.ChoiceField(widget=forms.Select, choices=options, label="", required=False)

class ItemsPerPageForm(forms.Form):
    options = (
        ("24", "24"),
        ("48", "48"),
        ("72", "72"),
        ("all", "All")
        )
    itemsPerPage = forms.ChoiceField(widget=forms.Select, choices=options, label="", required=False)

class CategoryForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    main_image = forms.ImageField(label='Main Image', required=True)

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        choices = [(c.name, c.name) for c in Category.objects.all()]
        choices.insert(0, ('', '----'))
        self.fields['parent'] = forms.ChoiceField(choices=choices, required=False)

    def clean(self):
        name = self.cleaned_data.get('name')
        parent = self.cleaned_data.get('parent')

        if name == parent:
            raise forms.ValidationError("No circular reference allowed")

        return self.cleaned_data

class EditCategoryForm(CategoryForm):
    main_image = forms.ImageField(label='Main Image', required=False)

MarketPlace/cart/views.py
# Create your views here.

MarketPlace/web_shop/templates/all_addresses.html
{% extends "base.html" %}
{% block title %}"All Addresses"{% endblock %}
{% block content %}
    {% if addresses%}
    <form method='post' action=''>
	  <input type="submit" name="Add New Address" value="Add New Address"/>
      <input type="submit" name="Delete" value="Delete"/>
      {% csrf_token %}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <tr>
        {% for entry in heading %}
          <th>{{ entry }}</th>
        {% endfor %}
      </tr>
        {% for entry in addresses %}
          <tr>
            <td><input type="checkbox" name="selected" value="{{entry.pk}}"></td>
            <td>{{entry.user}}</td>
            <td>{{entry.default}}</td>
            <td>{{entry}}</td>
            <td><a href="/editaddress/{{entry.pk}}">Update Address</a></td>
            <td><a href="/defaultaddress/{{entry.pk}}">Default Address</a></td>
          </tr>
        {% endfor %}
      </table>
      </div>
      <input type="submit" name="Add New Address" value="Add New Address"/>
      <input type="submit" name="Delete" value="Delete"/>
    </form>
    {% else %}
      <form method='post' action=''>
	  {% csrf_token %}
      <input type="submit" name="Add New Address" value="Add New Address"/>
      </form>
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          No matches found.
      </div>
    {% endif %}
{% endblock %}

MarketPlace/web_shop/templates/all_notifications.html
{% extends "base.html" %}
{% block title %}"Your Notifications"{% endblock %}
{% block content %}
    {% if notifications%}
    <script language="javascript">
      function toggle(source) {
        checkboxes = document.getElementsByName('selected');
        for(var i=0, n=checkboxes.length;i<n;i++) {
          checkboxes[i].checked = source.checked;
        }
      }

      function checkSelectAll() {
        if(isAll()) {
          document.getElementsByName('all')[0].checked=true;
        } else {
          document.getElementsByName('all')[0].checked=false;
        }
      }

      function isAll() {
        checkboxes = document.getElementsByName('selected');
        for(var i=0, n=checkboxes.length;i<n;i++) {
          if (!checkboxes[i].checked) {
            return false;
          }
        }
        return true;
      }
      </script>

    <form method='post' action=''>
      <input type="submit" name="Clear Selected" value="Clear Selected"/>
      {% csrf_token %}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <tr>
        <th><input type="checkbox" name="all" onClick="toggle(this)" /></th>
        {% for entry in heading %}
          <th>{{ entry }}</th>
        {% endfor %}
      </tr>
        {% for entry in notifications %}
          <tr>
            <td><input type="checkbox" name="selected" onchange="checkSelectAll()" value="{{entry.pk}}"></td>
            <td>{{entry.notif}}</td>
            <td><a href="{{entry.link}}">Go to page</a></td>
          </tr>
        {% endfor %}
      </table>
      </div>
      <input type="submit" name="Clear Selected" value="Clear Selected"/>
    </form>
    {% else %}
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          No matches found.
      </div>
    {% endif %}
{% endblock %}

MarketPlace/web_shop/templates/all_sales.html
{% extends "base.html" %}
{% block title %}"All Sales Orders"{% endblock %}
{% block content %}
  {% if request.user.is_superuser %}
    {% if sales%}
    <form method='post' action=''>
      <input type="submit" name="New" value="New"/>
      <input type="submit" name="Shipped" value="Shipped"/>
      <input type="submit" name="Completed" value="Completed"/>
      <input type="submit" name="Cancelled" value="Cancelled"/>
      {% csrf_token %}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <tr>
        {% for entry in heading %}
          <th>{{ entry }}</th>
        {% endfor %}
      </tr>
        {% for entry in sales %}
          <tr>
            <td><input type="checkbox" name="selected" value="{{entry.pk}}"></td>
            <td><a href="/sales-details/{{entry.pk}}">{{entry.pk}}</a></td>
            <td>{{entry.buyer}}</td>
            <td>{{entry.address}}</td>
            <td>{{entry.created_on}}</td>
            <td>{{entry.status}}</td>
          </tr>
        {% endfor %}
      </table>
      </div>
      <input type="submit" name="New" value="New"/>
      <input type="submit" name="Shipped" value="Shipped"/>
      <input type="submit" name="Completed" value="Completed"/>
      <input type="submit" name="Cancelled" value="Cancelled"/>
    </form>
    {% else %}
      <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          No matches found.
      </div>
    {% endif %}
  {% else %}
    {% if sales%}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <tr>
        {% for entry in heading %}
          <th>{{ entry }}</th>
        {% endfor %}
      </tr>
        {% for entry in sales %}
          <tr>
            <td><a href="/sales-details/{{entry.pk}}">{{entry.pk}}</a></td>
            <td>{{entry.buyer}}</td>
            <td>{{entry.address}}</td>
            <td>{{entry.created_on}}</td>
            <td>{{entry.status}}</td>
          </tr>
        {% endfor %}
      </table>
      </div>
      {% else %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            No matches found.
        </div>
      {% endif %}
    {% endif %}
{% endblock %}

MarketPlace/web_shop/templates/all_users.html
{% extends "base.html" %}
{% block title %}"All Users"{% endblock %}
{% block content %}
  {% if users %}
    <form method='post' action=''>
      <input type="submit" name="Enable" value="Enable"/>
      <input type="submit" name="Disable" value="Disable"/>
      {% csrf_token %}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
      <tr>
        {% for entry in heading %}
          <th>{{ entry }}</th>
        {% endfor %}
      </tr>
        {% for entry in users %}
          <tr>
            <td><input type="checkbox" name="selected" value="{{entry.username}}"></td>
            <td>{{entry.username}}</td>
            <td>{{entry.first_name}}</td>
            <td>{{entry.last_name}}</td>
            <td>{{entry.email}}</td>
            <td>{{entry.is_active}}</td>
          </tr>
        {% endfor %}
      </table>
      </div>
      <input type="submit" name="Enable" value="Enable"/>
      <input type="submit" name="Disable" value="Disable"/>
    </form>
  {% else %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        No matches found.
    </div>
  {% endif %}
{% endblock %}

MarketPlace/web_shop/templates/conversation.html
{% if history %}
  {% for entry in history %}
    {% if entry.origin == request.user.username %}
      <p><strong>You: {{entry.message | linebreaksbr}}</strong></p>
    {% else %}
      <p>{{ user }} : {{entry.message | linebreaksbr}}</p>
    {% endif %}
  {% endfor %}
{% else %}
  <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      Send a message to start a dialogue.
  </div>
{% endif %}

MarketPlace/web_shop/templates/detail.html
{% extends 'base.html' %}

{% block content %}
  {% if product.visible %}  
  <div class="row product">
  {% else %}
  <div class="row product p-list-not-visible">
  {% endif %} 
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 product_image_col">
        <img id="main_image" width="90%" src="/media/{{ product.main_image }}">
        <div class="other_images">
          <div id="product-image-0" class="prod_img col-md-3">
            <img width="100%" src="/media/{{ product.main_image }}">
          </div>
          {% for image in images %}
            <div id="product-image-{{ forloop.counter }}" class="prod_img col-md-3">
              <img width="100%" src="/media/{{ image.image }}">
            </div>
          {% endfor %}
        </div>
    </div>    
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 product_details_col">
      <div class="row prod_det">
    		<div>
            <h2>{{ product.name }}</h2>
        </div>
        <div>
    		    <h3>Price: {{ product.price }}</h3>
        </div>
        <div>
    		    <p>{{ product.description }}</p>
        </div>
        <div>
    		  <h4>Category: {{ product.category }}</h4>
        </div>
        <div id="product-tags">
        <h4>Tags:</h4>
        {% for tag in  tags%}
            <div class="tag">
              <p>{{ tag.name }}</p>
            </div>
          {% endfor %}
        </div>

        <div id="product-cart">
          {% if in_cart %}
          <form action="/product/{{ product.pk }}/cart" method="post">
              {% csrf_token %}          
              <label for="id_quantity">Quantity:</label>
              <input id="id_quantity" min="0" name="quantity" type="number" value="{{ in_cart }}">
              <input id="id_update" name="update" type="hidden" value="true">
              <input class="btn btn-default" type="submit" value="Update">
          </form>      
          <form action="/product/{{ product.pk }}/cart" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default" id="remove_cart">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>Remove From Cart</button>
            <!--<input type="submit" value="Remove from cart">-->
          </form>
          {% else %}
          <form action="/product/{{ product.pk }}/cart" method="post">
            {% csrf_token %}
            {{ form.quantity.label_tag }}
            {{ form.quantity }}
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart</button>
            <!-- <input class="btn btn-default" type="submit" value="Add to cart"> -->
          </form>
          {% endif %}
          {% if request.user.username %}
          {% if on_wishlist %}
          <form action="/product/{{ product.pk }}/wish" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default" id="remove_wish">
              <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>Remove From Wishlist</button>
            <!--<input type="submit" class="btn btn-default" value="Remove from Wishlist">-->
          </form>
          {% else %}        
          <form action="/product/{{ product.pk }}/wish" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-default" id="add_wish">
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>Add To Wishlist</button>
            <!--<input type="submit" class="btn btn-default" value="Add to Wishlist">-->
          </form>
          {% endif %}
          {% endif %}

          {% if request.user.is_superuser %}
          <div>
            <a href="/product/{{ product.pk }}/edit">
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Edit Product</button>
              <!-- <input class="btn btn-default" type="submit" value="Edit Product">-->
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>  
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $("#product-image-0 img").click(function(){
      var thmb = this;
      var src = this.src;
      $('#main_image').fadeOut(200,function(){
          $(this).fadeIn(200)[0].src = src;
      });
    });
    {% for image in images %}
    $("#product-image-{{ forloop.counter }} img").click(function(){
      var thmb = this;
      var src = this.src;
      $('#main_image').fadeOut(200,function(){
          $(this).fadeIn(200)[0].src = src;
      });
    });
    {% endfor %}
</script>
{% endblock %}